### PR TITLE
allow use of assume role credentials for S3 signed URLs

### PR DESCRIPTION
**Pull request by Caldrin**
To create SigV4 signed urls with credentials which were determined using
AssumeRole, the security token needs to be added to the request as well.

Signed-off-by: Maik Hentsche <caldrin@amazon.com>

### CODE REVIEW

**Comment by Grinnz** [comment]
There are a lot of unnecessary changes here. What is the purpose of changing the constructor?

**Comment by cop077** [comment]
> There are a lot of unnecessary changes here. What is the purpose of changing the constructor?

The security token is a parameter that need to be handed over to the constructor and stored in the object later on. The reason why we chose named parameters is to avoid handing over parameters at the wrong position. Additionally it is far more readable in our opinion. The code is still backwards compatible.

**Comment by Grinnz** [comment]
Thanks, I've implemented this in https://github.com/Grinnz/Net-Amazon-Signature-V4/commit/863ed529fd0e1c57eb0437b902cb3d8bd5a82ecb and https://github.com/Grinnz/Net-Amazon-Signature-V4/commit/97508cd962cd053ae5c36ed2aaa9f53d0ec746ce

**Comment by Grinnz** [comment]
These changes are released in 0.20. Thanks

**Pull request closed without merging**
