### PR TITLE
Stop double-escaping URI segments for S3

### PR DESCRIPTION
**Pull request by timmullin**
An update to this module addressed the need for the URI segments within
a request to be double-encoded.  However, S3 is an exception
to this and double-encoding the URI segments will cause
the signature to be invalid.

From Step 2 in "creating a canonical request" in the following document:
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

"Normalize URI paths according to RFC 3986. Remove redundant and
relative path components. Each path segment must be URI-encoded twice
(except for Amazon S3 which only gets URI-encoded once)."

This is my proposed fix for issue:
https://rt.cpan.org/Ticket/Display.html?id=128728

### CODE REVIEW

**Comment by castaway** [comment]
Hi, looks like Paws runs into this issue as well (as it uses this module), any chance this PR could be applied, or something similar  @Grinnz ?

**Comment by castaway** [comment]
@timmullin mebbe you can add a test as well?

**Comment by Grinnz** [comment]
Sorry I am not a very active maintainer here. The risk of breakage is very great and I don't have a good handle on whether any given changes are appropriate. I'm happy to merge this with your confirmation but tests would also be helpful.

**Comment by castaway** [comment]
Thanks for the update, the quote from the official docs above "except for S3" is a good indication that we're on the right path. Happy to add tests if @timmullin doesn't get to it.

**Comment by Grinnz** [comment]
This is released in 0.20. Test updates still appreciated if anyone is up for it.

**Pull request merged**
